#!/usr/bin/python3
import sys,re
import subprocess
import os
import tempfile
import pygit2
from time import time
from math import floor
from pprint import pprint

def getrepo():
  cmd = ['git', 'rev-parse', '--git-dir']
  child = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  git_dir, junk = child.communicate()
  git_dir = git_dir.strip()
  print(git_dir)

def git_clone(repo, dir, branch=None):
  cmd = ['git', 'clone']
  if branch != None:
    cmd += ['-b', branch]

  cmd += [repo, dir]

  rc = subprocess.call(cmd)
  if rc != 0:
    print('Failed ' + ' '.join(cmd))

def git_push(repo, remote, branch):
  cmd = ['git', '--git-dir={}/.git'.format(repo), 'push', remote, branch]

  rc = subprocess.call(cmd)
  if rc != 0:
    print('Failed ' + ' '.join(cmd))

def jekyll(source, target):
  cmd = ['jekyll', '--no-auto', source, '{}/_site'.format(target)]
  rc = subprocess.call(cmd)
  if rc != 0:
    print('Failed ' + ' '.join(cmd))

def main():
  repo = os.path.realpath('.')
  for line in sys.stdin:
    print(line)
    m = re.search(r'^([0-9a-f]{40}) ([0-9a-f]{40}) refs/heads/([0-9a-zA-Z]+)$', line)
    if m:
      print("Processing {}".format(m.group(3)))
      branch = m.group(3)
      build_branch = 'build-{}'.format(branch)
      tmp_git = tempfile.TemporaryDirectory()
      #tmp_git = '/tmp/tmp-work'
      tmp_git_master = '{}/{}'.format(tmp_git.name, branch)
      tmp_git_build  = '{}/build-{}'.format(tmp_git.name, branch)

      os.mkdir(tmp_git_master)
      os.mkdir(tmp_git_build)

      git_clone(repo, tmp_git_master, branch)
      git_clone(repo, tmp_git_build)

      master_repo = pygit2.Repository(tmp_git_master)
      build_repo  = pygit2.Repository(tmp_git_build)

      head =  build_repo.lookup_reference('HEAD')
      
      try:
        ref = build_repo.lookup_reference('refs/remotes/origin/{}'.format(build_branch))
        parents = [ref.oid]
      except KeyError as e:
        parents = []

      head.target = 'refs/heads/{}'.format(build_branch)
      pprint(parents)
      
      
      jekyll(tmp_git_master, tmp_git_build)

      #tb = build_repo.TreeBuilder()
      build_index = build_repo.index

      for dirpath, dirnames, filenames in os.walk(tmp_git_build):
        m = re.search(r'\.git', dirpath)
        if m:
          continue
        #for dn in dirnames:
        #  m = re.search(r'\.git', dn)
        #  if m:
        #    continue
        #  build_index.add(os.path.join(dirpath, dn), 0)
        for fn in filenames:
          build_index.add(os.path.relpath(os.path.join(dirpath, fn), tmp_git_build), 0)

      build_index.write()
      oid       = build_index.write_tree()
      tree      = build_repo[oid]
      author    = pygit2.Signature('jekyll', 'jekyll@alexchamberlain.co.uk', floor(time()), 0)
      committer = pygit2.Signature('git',       'git@alexchamberlain.co.uk', floor(time()), 0)
      build_repo.create_commit('refs/heads/{}'.format(build_branch), author, committer, "Build", tree.oid, parents)

      git_push(tmp_git_build, 'origin', build_branch)
    else:
      print("Ignoring {}".format(line))

if __name__=='__main__':
  main()
